id: I458F265B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T06:22:36+00:00'
last_modified: '2022-06-08T09:08:07.113511+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27913
  title: རིས་མེད་ཆོས་འབྱུང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    1E54:
      image_group_id: I4514
      title: ''
      total_pages: 161
      order: 1
      base_file: 1E54.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
