id: P006873
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 12:27:54.907052
source_metadata:
  id: bdr:W27913
  title: རིས་མེད་ཆོས་འབྱུང
  author: ''
  volumes:
    6ac2d0b4a8244bcc929816e7f5c0c8d7:
      image_group_id: I4514
      title: ''
      volume_number: 1
      total_pages: 161
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
